
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Frecuento2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Reserva = new HashSet<Reserva>();

    }


    public int Id_Cliente { get; set; }

    public string Nombre { get; set; }

    public string Apellidos { get; set; }

    public string Dirección { get; set; }

    public string Código_Postal { get; set; }

    public System.DateTime Fecha_Nacimiento { get; set; }

    public int Teléfono { get; set; }

    public string Email { get; set; }

    public string DNI { get; set; }

    public string Nº_Cuenta { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

}

}
