
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Frecuento2.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cliente()
    {

        this.Reserva = new HashSet<Reserva>();

    }


        public int Id_Cliente { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(50, ErrorMessage = "Longuitud debe ser entre 3 y 50.", MinimumLength = 3)]
        public string Nombre { get; set; }
        [Display(Name = "Apellidos")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(50, ErrorMessage = "Longuitud debe ser entre 3 y 50.", MinimumLength = 3)]
        public string Apellidos { get; set; }
        [Display(Name = "Dirección")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(50, ErrorMessage = "Longuitud debe ser entre 3 y 50.", MinimumLength = 3)]
        public string Dirección { get; set; }
         public string Código_Postal { get; set; }
        [Display(Name = "Fecha de Nacimiento")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime Fecha_Nacimiento { get; set; }
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [RegularExpression(@"^(\([0-9]{3}\)|[0-9]{3}-)[0-9]{3}-[0-9]{3}|(\([0-9]{3}\)|[0-9]{3})[0-9]{3}[0-9]{3}$",
          ErrorMessage = "Teléfono incorrecto.")]
        public int Teléfono { get; set; }
        [Display(Name = "Correo electrónico")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*",
           ErrorMessage = "Dirección de Correo electrónico incorrecta.")]
        [StringLength(100, ErrorMessage = "Longitud máxima 100")]
        public string Email { get; set; }
        [RegularExpression("^(([A-Z]\\d{8})|(\\d{8}[A-Z]))$", ErrorMessage = "DNI incorrecto")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Ingrese su DNI")]
        public string DNI { get; set; }
        [Display(Name = "Número de Cuenta")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(24, ErrorMessage = "Formato debe ser ES y 22 dígitos.", MinimumLength = 24)]
        public string Nº_Cuenta { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

}

}
