
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Frecuento2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empresa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empresa()
    {

        this.EvenEmpre = new HashSet<EvenEmpre>();

        this.Reserva = new HashSet<Reserva>();

        this.ServiEmpre = new HashSet<ServiEmpre>();

    }


    public int Id_Empresa { get; set; }

    public string Nombre { get; set; }

    public string Dirección { get; set; }

    public int Teléfono { get; set; }

    public int Nº_Empleados { get; set; }

    public string Nº_Cuenta { get; set; }

    public string Email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EvenEmpre> EvenEmpre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ServiEmpre> ServiEmpre { get; set; }

}

}
