
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Frecuento2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EvenEmpre
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EvenEmpre()
    {

        this.Reserva = new HashSet<Reserva>();

        this.evenser = new HashSet<evenser>();

    }


    public int Id_Empresa { get; set; }

    public int Precio_Base { get; set; }

    public int Id_Tipo_Evento { get; set; }

    public int Id_EvenEmpre { get; set; }



    public virtual Empresa Empresa { get; set; }

    public virtual Tipo_Evento Tipo_Evento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reserva> Reserva { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<evenser> evenser { get; set; }

}

}
