
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Frecuento2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ServiEmpre
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ServiEmpre()
    {

        this.evenser = new HashSet<evenser>();

    }


    public int Id_Tipo_Servicio { get; set; }

    public int Precio_Servicio { get; set; }

    public int Id_Empresa { get; set; }

    public int Id_ServiEmpre { get; set; }



    public virtual Empresa Empresa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<evenser> evenser { get; set; }

    public virtual Tipo_Servicio Tipo_Servicio { get; set; }

}

}
