
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Frecuento2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tipo_Evento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tipo_Evento()
    {

        this.EvenEmpre = new HashSet<EvenEmpre>();

    }


    public int Id_Tipo_Evento { get; set; }

    public string Descripción { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EvenEmpre> EvenEmpre { get; set; }

}

}
