//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frecuento2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenser
    {
        public int Id { get; set; }
        public int Id_Servi { get; set; }
        public int Id_Event { get; set; }
    
        public virtual EvenEmpre EvenEmpre { get; set; }
        public virtual ServiEmpre ServiEmpre { get; set; }
    }
}
